language: julia
os:
    - osx
    - linux
julia:
    - 0.3
    - nightly
notifications:
    email: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.clone(pwd()); Pkg.build("Morsel"); Pkg.test("Morsel"; coverage=true)';
    - julia -e 'cd(Pkg.dir("Morsel")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
